[project]
name = "backend"
version = "0.1.0"
description = "backend "
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.9",
    "djangorestframework>=3.16.1",
    "psycopg2-binary>=2.9.11",
]
